package hmm.dota2dqn.common;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;



public class Memory {	
	private List<MemoryEntry> memories;
	public Memory(){		
		/*
		  The state is generated by Dota 2 every 0.33 second (Please check addon_game_mode.lua) so if a game takes 4 hours,
		  the number of states will be almost 4*60*60*3=43200 which is not a big size for saving in memory. Therefore, there is no
		  need to limit memory size.
		*/
		this.memories=new ArrayList<MemoryEntry>();
	}
	public void addToMemory(State observation, State lastState, int action,double reward,boolean isfinal) {
		MemoryEntry newMemory = new MemoryEntry(lastState,action,observation,reward,isfinal);
		memories.add(newMemory);		
	}
	public List<MemoryEntry> getMiniBatch(){
		Configs conf= new Configs();
		//Randomize memory list
		Collections.shuffle(memories);		
		return memories.subList(0,conf.getMiniBatchSize() );
		
	}
	public int getMemorySize(){
		return memories.size();
	}
}
